### ISSUE TITLE
[upload] Initial draft creation doesn't validate files

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#851]
Package version (if known): April release

When saving a draft with errors for the first time (draft not existing yet), validation for presence of files or metadata-only option is not checked it seems.

## Steps to Reproduce
1. Go to 'uploads/new'
2. Click on 'Save Draft' immediately, *don't* fill anything
3. See warnings for other fields but not for "Files" 

## Expected behavior
See warnings for other fields and for Files

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/1932651/118868044-baf0d680-b8b1-11eb-99a3-ba2943e0fbaf.png)

**Comment by lnielsen** [comment]
I'm right now getting a 500 error when following the reproduce steps.

**Comment by fenekku** [comment]
No 500 on my side, but original issue still stands as of v8

**Comment by ppanero** [comment]
@zzacharo is this fixed by the latest PR?

**Comment by tmorrell** [comment]
I'm still seeing what is likely the same issue in v9-rc1. Here is another example:

1. Create a new record
2. Do *not* upload files or check "Metadata-only"
3. Fill out required metadata
4. Save draft
5. System responds "Record successfully saved", but the "Submit for review"/"Publish" button is not active. No error message is shown noting that files are missing.

If you click "Save draft" again you'll get the expected error message.
